server {
    listen 8085;
    server_name localhost;

    root /vps/mdz-develop;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Static file caching for optimized asset loading
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mp4|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
